copy new ebs to workspace

diff --git a/jenkins/JenkinsfileExperimentalEB b/jenkins/JenkinsfileExperimentalEB
--- a/jenkins/JenkinsfileExperimentalEB
+++ b/jenkins/JenkinsfileExperimentalEB
@@ -2,7 +2,7 @@
 
 def methods
 def machinesList
-/* 
+/*
  Initialization: checkout the production repository to load the files:
  - "util.groovy" with the functions used in the pipeline scripts
  - "Machines.groovy" with the list and properties of HPC systems
@@ -15,10 +15,10 @@ stage('Initialization') {
     }
 }
 
-/* 
- Machine Selection: 
+/*
+ Machine Selection:
  - filters the user defined parameter "machines", accessible though "params.machines"
- - defines the runtime HPC systems of the project "machinesToRun" 
+ - defines the runtime HPC systems of the project "machinesToRun"
  - defines the configuration of the runtime HPC systems "machinesConfiguration"
 */
 def machineConfigurations = []
@@ -38,7 +38,7 @@ stage('Machine Selection') {
     }
 }
 
-/* 
+/*
  Build Stage: configures parallel builds for the different "machinesToRun"
  Loop over all systems in "machineConfigurations":
   - if the machine has multiple architectures, starts a sub-loop over architectures
@@ -53,11 +53,11 @@ stage('Build Stage') {
         def architectures = system.architectures
         def machineName = machine.name
         for (item in architectures) {
-            /* define architecture and machineLabel 
+            /* define architecture and machineLabel
                to use them in parallel builds */
             def architecture = item
             def machineLabel = architecture == "" ?
-               machineName : 
+               machineName :
                "$machineName-$architecture"
             builds["$machineLabel"] = {
                 node(machineName) {
@@ -65,8 +65,8 @@ stage('Build Stage') {
 
                     /* define unusePath */
                     if (machine.unusePath != '') {
-                        def unusePath = architecture == '' ?  
-                            "$machine.unusePath" : 
+                        def unusePath = architecture == '' ?
+                            "$machine.unusePath" :
                             "$machine.unusePath".replace('ARCH', architecture)
                     }
 
@@ -76,7 +76,7 @@ stage('Build Stage') {
                         "module load cdt/${params.cdt_version} daint-$architecture EasyBuild-custom/cscs"
 
                     /* define command to switch EasyBuild version*/
-                    def switcheasybuild = 
+                    def switcheasybuild =
                         "module switch EasyBuild EasyBuild/${params.eb_version}"
 
                     /* define toolchain names and corresponding EasyBuild recipes */
@@ -85,8 +85,8 @@ stage('Build Stage') {
                     println "Current toolchains: $current_tc"
 
                     /* define command to build new toolchains */
-                    def build_toolchains = architecture == "" ? 
-                        "srun -u -J $env.JOB_BASE_NAME --account=${params.account} -t 00:05:00 eb $current_tc --hidden --try-software-version=${params.cdt_version}" :  
+                    def build_toolchains = architecture == "" ?
+                        "srun -u -J $env.JOB_BASE_NAME --account=${params.account} -t 00:05:00 eb $current_tc --hidden --try-software-version=${params.cdt_version}" :
                         "srun -u -C $architecture -J $env.JOB_BASE_NAME --account=${params.account} -t 00:05:00 eb $current_tc --hidden --try-software-version=${params.cdt_version}"
 
                     /* build new toolchains */
@@ -128,25 +128,38 @@ stage('Build Stage') {
                         export EASYBUILD_EXTERNAL_MODULES_METADATA="$WORKSPACE/easybuild/cray_external_modules_metadata-${params.cdt_version}.cfg"
 
                         # initialize production list
-                        echo > $WORKSPACE/jenkins-builds/${prod_file}
+                        rm $WORKSPACE/jenkins-builds/$prod_file
                         build_list=\$(awk -v cdt=${params.cdt_current} '{if(\$1~cdt) print \$1}' $WORKSPACE/jenkins-builds/$machineLabel | grep -v classic | grep -v Amber)
                         for recipe in \${build_list}; do
                             status=0
                             echo -e "\nBuilding \$recipe"
                             srun -u -C $architecture -J $env.JOB_BASE_NAME --account=${params.account} -t 01:00:00 eb --try-toolchain-version=${params.cdt_version} -r \$recipe
                             status=\$[status+\$?]
-                            # save successful builds in production file 
-                            if [ \$status -eq 0 ]; then 
-                                echo \$recipe >> $WORKSPACE/jenkins-builds/${prod_file}
+                            # save successful builds in production file
+                            if [ \$status -eq 0 ]; then
+                                success+=(\$recipe)
+                                echo eb success: \${#success[@]} \$recipe : \$success
+                                new_eb=\$(echo \$recipe | sed -E 's/(Cray.+)-${params.cdt_current}/\\1-${params.cdt_version}/')
+                                new_path=\$(echo \$new_eb | sed -E 's@-(.*)\\.eb@/\\1@')
+                                ls -lh ${params.eb_prefix}/$machineLabel/${params.cdt_version}/software/\$new_path/easybuild/reprod/\$new_eb
+                                find $WORKSPACE -name \$recipe | xargs dirname | xargs cp ${params.eb_prefix}/$machineLabel/${params.cdt_version}/software/\$new_path/easybuild/reprod/\$new_eb
+                                echo \$new_eb >> $WORKSPACE/jenkins-builds/$prod_file
                                 # TO DO: add successful recipes to GitHub PR
                             else
+                                failed+=(\$recipe)
+                                echo eb failed: \${#failed[@]} \$recipe : \$failed
                                 continue
                                 # TO DO: open Jira issue or GitHub WIP PR
                             fi
                         done
-                        exit \$status
+
+                        echo original: $WORKSPACE/jenkins-builds/$prod_file
+                        cat $WORKSPACE/jenkins-builds/$prod_file
+
+#                        echo sed: $WORKSPACE/jenkins-builds/$prod_file
+#                        sed -E 's/Cray(.*)-${params.cdt_current}/Cray\1-${params.cdt_version}/g' $WORKSPACE/jenkins-builds/$prod_file
+
 #                        # find production dependencies:
-#                        #cat $WORKSPACE/jenkins-builds/$prod_file
 #                        awk '{print \$1}' $WORKSPACE/jenkins-builds/$prod_file | xargs -IF eb F -Dr 1> $WORKSPACE/deps.out || true
 #                        #cat $WORKSPACE/deps.out
 #                        cat $WORKSPACE/deps.out | grep ' \\* \\[.\\] ' | sed 's@^[^/]*/@@g' | awk '{print \$1}' | xargs basename -a | grep '\\-Cray.*-'${params.cdt_current} | sort | uniq | xargs -IF find $WORKSPACE -name F 1> $WORKSPACE/deps_clean.out
@@ -174,11 +187,15 @@ stage('Build Stage') {
 #                        # build all new recipes
 #                        status=0
 #                        find $WORKSPACE/easybuild/easyconfigs -name *-Cray*-${params.cdt_version}*.eb | xargs -IF srun -u -C $architecture -J $env.JOB_BASE_NAME --account=${params.account} -t 01:00:00 eb -r F
-#                        rm $WORKSPACE/*.out
-#                        git -C $WORKSPACE status
-#
-#                        status=\$[status+\$?]
-#                        exit \$status
+
+                        rm $WORKSPACE/*.out
+
+                        echo $SCRATCH
+                        chmod a+r -R $SCRATCH/ExperimentalEB/
+                        git -C $WORKSPACE status
+
+                        status=\$[status+\$?]
+                        exit \$status
                     """)
                 }
             }
