copy generated toolchains to workspace

diff --git a/jenkins/JenkinsfileExperimentalEB b/jenkins/JenkinsfileExperimentalEB
--- a/jenkins/JenkinsfileExperimentalEB
+++ b/jenkins/JenkinsfileExperimentalEB
@@ -78,20 +78,13 @@ stage('Build Stage') {
                     def switcheasybuild = 
                         "module switch EasyBuild EasyBuild/$eb_version"
 
-                    def toolchains = ['CrayCCE', 'CrayGNU', 'CrayIntel', 'CrayPGI']
-
-                    /* make a copy of cdt_current toolchains using the new cdt_version */
-                    for (toolchain in toolchains) {
-                        def tc_path = "$WORKSPACE/easybuild/easyconfigs/c/$toolchain"
-                        sh "cp ${tc_path}/${toolchain}-${params.cdt_current}.eb ${tc_path}/${toolchain}-${params.cdt_version}.eb"
-                    }
-
-                    def new_tc = toolchains.collect{"$it-${params.cdt_version}.eb"}.join(' ')
-                    sh "echo $new_tc"
+                    def toolchains = ['CrayGNU', 'CrayIntel', 'CrayPGI']  // , 'CrayCCE']
+                    def current_tc = toolchains.collect{"$it-${params.cdt_current}.eb"}.join(' ')
+                    sh "echo $current_tc"
 
                     def command = architecture == "" ? 
                         "srun -u -J $env.JOB_BASE_NAME -t 00:01:00 eb --show-config" :  
-                        "srun -u -C $architecture -J $env.JOB_BASE_NAME -t 00:01:00 eb --hidden $new_tc"
+                        "srun -u -C $architecture -J $env.JOB_BASE_NAME -t 00:01:00 eb -f $current_tc --hidden --try-toolchain-version=${params.cdt_version}"
 
                     sh("""#!/bin/bash -l
                         export EASYBUILD_PREFIX="$params.eb_prefix/$machineLabel"
@@ -108,23 +101,34 @@ stage('Build Stage') {
                         awk '{print \$1}' $WORKSPACE/jenkins-builds/$machineLabel | xargs -IF eb F -Dr 1> $WORKSPACE/deps.out || true
                         cat $WORKSPACE/deps.out | grep ' \\* \\[.\\] \$CFGS' | sed 's@.*\$CFGS/@@g' | awk '{print \$1}' | xargs basename -a | grep '\\-Cray.*-19.10' | sort | uniq | xargs -IF find $WORKSPACE -name F 1> $WORKSPACE/deps_clean.out
                         cat $WORKSPACE/deps_clean.out
+                        status=0
 
                         # upgrade to new cdt_version
                         cat $WORKSPACE/deps_clean.out | xargs $WORKSPACE/easybuild/scripts/upgrade-tc.py --metadata easybuild/cray_external_modules_metadata-${params.cdt_version}.cfg --toolchain-prefix Cray --version $params.cdt_version --filenames
                         rm $WORKSPACE/*.out
                         git -C $WORKSPACE status
 
-                        # build cdt
+                        # build cdt for target version
                         echo -e "\nRunning command: \n$command"
-                        status=0
                         $command
 
                         # build all new recipes
                         find $WORKSPACE/easybuild/easyconfigs -name *-Cray*-${params.cdt_version}*.eb | xargs eb -r
-                        git -C $WORKSPACE status
+
+                        # TODO: remove to exit on error
+                        status=0
+                        ls \$EASYBUILD_PREFIX/software/Cray*/${params.cdt_version}/easybuild/reprod/*.eb || true
 
                         status=\$[status+\$?]
                         exit \$status""")
+
+                    /* copy generated toolchains to workspace */
+                    for (toolchain in toolchains) {
+                        def source = "$params.eb_prefix/$machineLabel/software/${toolchain}/${params.cdt_version}/easybuild/reprod/${toolchain}-${params.cdt_version}.eb"
+                        def target = "$WORKSPACE/easybuild/easyconfigs/c/$toolchain/${toolchain}-${params.cdt_version}.eb"
+                        sh "cp ${source} ${target}"
+                    }
+                    sh "git -C $WORKSPACE status"
                 }
             }
         }
