reconcile passing recipes

diff --git a/jenkins/JenkinsfileExperimentalEB b/jenkins/JenkinsfileExperimentalEB
--- a/jenkins/JenkinsfileExperimentalEB
+++ b/jenkins/JenkinsfileExperimentalEB
@@ -169,7 +169,7 @@ stage('Build Stage') {
                         # build recipes
                         for recipe in \${build_list}; do
                             status=0
-                            new_recipe=\$(echo \$recipe | sed 's/${params.cdt_current}/${params.cdt_version}/')
+                            new_recipe=\$(echo \$recipe | sed -E 's/(Cray.+)-${params.cdt_current}/\\1-${params.cdt_version}/')
                             echo -e "\nBuilding \$new_recipe"
                             eb \$recipe --try-toolchain-version=${params.cdt_version} -Dr 2>&1 | grep -iv "== temporary"
 
@@ -200,9 +200,6 @@ stage('Build Stage') {
                         # print successful and failed builds
                         echo -e "\nSuccessful Builds: \${#success[@]} \n\${success[@]}"
                         echo -e "\nFailed Builds: \${#failed[@]} \n\${failed[@]}"
-
-                        # return the number of failed Builds
-                        exit \${#failed[@]}
                     """)
                 }
             }
@@ -212,29 +209,51 @@ stage('Build Stage') {
     try {
         parallel builds
 
-        //// merge workspaces and create PR's
-        //node('dom') {
-        //    sh("""#!/bin/bash -l
-        //        git -C $WORKSPACE status
+        // merge workspaces and create PR's
+        node('dom') {
+            sh("""#!/bin/bash -l
+                module load daint-gpu
+                module load hub
 
-        //        cp -rf \$SCRATCH/*/workspace/ExperimentalEB*/* $WORKSPACE
-        //        rm $WORKSPACE/*.out
-        //        git -C $WORKSPACE status
-        //        git -C $WORKSPACE --no-pager diff --stat
-        //        echo \$SCRATCH/*/workspace/ExperimentalEB*/ | sed 's@ @\\n@g'
+                echo \$SCRATCH/*/workspace/ExperimentalEB*/ | sed 's@ @\\n@g'
+                pwd
 
-        //        echo $WORKSPACE
-        //        echo $SCRATCH
-        //        pwd
+                ## create git branch or update if exists
+                git checkout -b exp/${params.cdt_version} || (git checkout exp/${params.cdt_version} && git pull)
 
-        //        wc $SCRATCH/$env.JOB_BASE_NAME-*-failed.log
-        //        head $SCRATCH/$env.JOB_BASE_NAME-*-failed.log | sed 's@ @\\n@g'
-        //        wc $SCRATCH/$env.JOB_BASE_NAME-*-success.log
-        //        head $SCRATCH/$env.JOB_BASE_NAME-*-success.log | sed 's@ @\\n@g'
-        //        # TO DO: add successful recipes to GitHub PR
-        //        # TO DO: open Jira issue or GitHub WIP PR with failed recipes
-        //    """)
-        //}
+                failed_files="${params.eb_prefix}/*/${params.cdt_version}/failed.txt"
+                success_files="${params.eb_prefix}/*/${params.cdt_version}/success.txt"
+
+                wc \$failed_files
+                failed=\$(cat \$failed_files | sed 's@ @\\n@g' | sort | uniq)
+                echo \${failed[@]}
+                # TO DO: open Jira issue or GitHub WIP PR with failed recipes
+
+                wc \$success_files
+                success=\$(cat \$success_files | sed 's@ @\\n@g' | sort | uniq)
+                echo \${success[@]}
+                for new_recipe in \${success[@]}; do
+                    # copy new recipe onto the correct folder
+                    old_recipe=\$(echo \$new_recipe | sed -E 's/(Cray.+)-${params.cdt_version}/\\1-${params.cdt_current}/')
+                    new_path=\$(echo \$new_recipe | sed -E 's@-(.*)\\.eb@/\\1@')
+                    ls -lh ${params.eb_prefix}/*/${params.cdt_version}/software/\$new_path/easybuild/reprod/\$new_recipe
+                    find $WORKSPACE -name \$old_recipe
+                    find $WORKSPACE -name \$old_recipe | xargs dirname | xargs cp -f ${params.eb_prefix}/*/${params.cdt_version}/software/\$new_path/easybuild/reprod/\$new_recipe
+                done
+
+                # TO DO: add successful recipes to GitHub PR
+                rm $WORKSPACE/*.out
+                git -C $WORKSPACE add easybuild/easyconfigs
+                git -C $WORKSPACE status
+                git -C $WORKSPACE --no-pager diff --stat
+                git commit -m "Add recipes for cdt/${params.cdt_version}"
+                git push origin HEAD
+                # hub pull-request -m "WIP [dom] Add recipes for cdt/${params.cdt_version}"
+
+                # return the number of failed Builds
+                exit \${#failed[@]}
+            """)
+        }
         currentBuild.result = "SUCCESS"
     } catch(err) {
         if (err.toString().contains('exit code 143')) {
@@ -251,33 +270,3 @@ stage('Build Stage') {
         }
     }
 }
-
-/* Needed in preparation of the GitHub pull request */
-//#/*
-//#                                new_eb=\$(echo \$recipe | sed -E 's/(Cray.+)-${params.cdt_current}/\\1-${params.cdt_version}/')
-//#                                new_path=\$(echo \$new_eb | sed -E 's@-(.*)\\.eb@/\\1@')
-//#                                ls -lh ${params.eb_prefix}/$machineLabel/${params.cdt_version}/software/\$new_path/easybuild/reprod/\$new_eb
-//#                                find $WORKSPACE -name \$recipe | xargs dirname | xargs cp ${params.eb_prefix}/$machineLabel/${params.cdt_version}/software/\$new_path/easybuild/reprod/\$new_eb
-//#                                echo \$new_eb >> $WORKSPACE/jenkins-builds/$prod_file
-//#                        done
-//#
-//#                        echo original: $WORKSPACE/jenkins-builds/$prod_file
-//#                        cat $WORKSPACE/jenkins-builds/$prod_file
-//#
-//#
-//#                        rm $WORKSPACE/*.out
-//#
-//#                        chmod a+r -R $SCRATCH/ExperimentalEB/
-//#                        git -C $WORKSPACE status
-//#
-//#                        echo $WORKSPACE
-//#                        echo $SCRATCH
-//#*/
-
-// alternative creation of toolchains without --try-...
-//#                        tcdir=\$(find . -type f -name "Cray*-${params.cdt_current}.eb" -execdir pwd ';')
-//#                        for dir in \$tcdir; do
-//#                         tcname=\$(basename \$dir) 
-//#                         sed 's/${params.cdt_current}/${params.cdt_version}/' \$dir/\$tcname-${params.cdt_current}.eb > \$dir/\$tcname-${params.cdt_version}.eb 
-//#                         eb \$tcname-${params.cdt_version}.eb --hidden
-//#                        done
